package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"backend/db/repository/liquorRepository"
	"backend/graph/graphModel"
	"backend/middlewares/auth"
	"backend/middlewares/customError"
	"backend/util/helper"
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/sirupsen/logrus"
)

// PostTag is the resolver for the postTag field.
func (r *mutationResolver) PostTag(ctx context.Context, input graphModel.TagInput) (*graphModel.Tag, error) {
	uId, err := auth.GetId(ctx)
	if err != nil {
		return nil, err
	}
	lId, err := helper.ObjectIDFromHex(input.LiquorID)
	if err != nil {
		return nil, err
	}
	tags, err := r.LiquorRepo.GetTagNames(ctx, lId)
	if err != nil {
		return nil, err
	}
	// すでに同じタグが存在するか確認（大文字小文字を区別しない場合は strings.EqualFold を使ってもOK）
	for _, existing := range tags {
		if existing == input.Text {
			// 重複が見つかったのでエラーを返す
			return nil, customError.NewError(errors.New("タグが重複しています"), customError.Params{
				StatusCode: http.StatusBadRequest,
				ErrCode:    "TAG_POST_DUPLICATE",
				UserMsg:    "タグが重複しています。",
				Level:      logrus.InfoLevel,
				Input:      fmt.Sprintf("liquorID: %s, input.text: %s", input.LiquorID, input.Text),
			})
		}
	}
	tag, err := r.LiquorRepo.PostTag(ctx, lId, uId, input.Text)
	if err != nil {
		return nil, err
	}
	return tag.ToGraphQL(), nil
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, id string) (bool, error) {
	tId, err := helper.ObjectIDFromHex(id)
	if err != nil {
		return false, err
	}
	err = r.LiquorRepo.DeleteTag(ctx, tId)
	if err != nil {
		return false, err
	}
	return true, nil
}

// GetTags is the resolver for the getTags field.
func (r *queryResolver) GetTags(ctx context.Context, liquorID string) ([]*graphModel.Tag, error) {
	lId, err := helper.ObjectIDFromHex(liquorID)
	if err != nil {
		return nil, err
	}
	tags, err := r.LiquorRepo.GetTags(ctx, lId)
	if err != nil {
		return nil, err
	}
	return liquorRepository.TagsToGraphQL(tags), nil
}

// SearchLiquorsByTag is the resolver for the searchLiquorsByTag field.
func (r *queryResolver) SearchLiquorsByTag(ctx context.Context, tag string) ([]*graphModel.Liquor, error) {
	// タグから日本酒IDのリストを取得
	liquorIds, err := r.LiquorRepo.SearchLiquorsByTag(ctx, tag)
	if err != nil {
		return nil, err
	}

	// IDがない場合は空の配列を返す
	if len(liquorIds) == 0 {
		return []*graphModel.Liquor{}, nil
	}

	// IDから日本酒データを取得
	liquors, err := r.LiquorRepo.GetLiquorsByIds(ctx, liquorIds)
	if err != nil {
		return nil, err
	}

	// GraphQL形式に変換
	result := make([]*graphModel.Liquor, 0, len(liquors))
	for i := range liquors {
		result = append(result, liquors[i].ToGraphQL())
	}

	return result, nil
}
