# Backend Lefthook Configuration
# This file contains backend-specific hooks
# It should be executed from the backend directory context

pre-commit:
  skip: true

post-commit:
  commands:
    check-schema-changes:
      glob: "graph/schema/*.graphqls"
      run: |
        # Check if any .graphqls files were changed in the last commit
        if git diff HEAD~1 HEAD --name-only | grep -q "backend/graph/schema/.*\.graphqls"; then
          echo ""
          echo "⚠️  =========================================="
          echo "⚠️  GraphQLスキーマが変更されました！"
          echo "⚠️  =========================================="
          echo ""
          echo "フロントエンドの型定義を更新してください："
          echo ""
          echo "  1. バックエンドを起動してください（まだの場合）"
          echo "  2. cd front"
          echo "  3. npm run fetch-schema"
          echo "  4. npm run codegen"
          echo ""
          echo "これらのコマンドを実行しないと、フロントエンドで"
          echo "ビルドエラーや型エラーが発生する可能性があります。"
          echo ""
        fi

