# Backend Lefthook Configuration
# This file contains backend-specific pre-commit hooks
# It should be executed from the backend directory context

pre-commit:
  parallel: true
  commands:
    # Go構文チェック
    go-fmt:
      root: "backend/"
      glob: "*.go"
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "✗ Go files are not formatted:"
          gofmt -l .
          echo "Run 'make fmt' to fix"
          exit 1
        else
          echo "✓ Go formatting check passed"
        fi
    
    # Go静的解析
    go-lint:
      root: "backend/"
      glob: "*.go"
      run: |
        if command -v golangci-lint &> /dev/null; then
          # --new-from-rev を使用して変更されたファイルのみをチェック
          golangci-lint run --new-from-rev=HEAD~1
        else
          echo "⚠ golangci-lint not installed. Skipping linting."
          echo "  Install with: make install-tools"
        fi
    
    # Go vet
    go-vet:
      root: "backend/"
      glob: "*.go"
      run: go vet ./...
    
    # GraphQLスキーマ検証
    graphql-validate:
      root: "backend/"
      glob: "graph/schema/*.graphqls"
      run: |
        echo "Validating GraphQL schema..."
        go run github.com/99designs/gqlgen generate --config gqlgen.yml
        if [ $? -eq 0 ]; then
          echo "✓ GraphQL schema validation passed"
          # 注意: 生成されたファイルは手動でgit addする必要があります
          if git diff --quiet graph/generated/ graph/graphModel/; then
            echo "  No changes in generated files"
          else
            echo "  ⚠ Generated files have been updated. Please add them to your commit:"
            echo "    git add backend/graph/generated/ backend/graph/graphModel/"
          fi
        else
          echo "✗ GraphQL schema validation failed"
          exit 1
        fi
