# .lefthook.yml
pre-push:
  parallel: true
  commands:
    eslint:
      root: "front/"
      run: npm run lint
    prettier:
      root: "front/"
      run: npm run format

post-push:
  commands:
    message:
      run: echo "プッシュが完了しました。"
