import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  schema: '../backend/graph/schema/*.graphqls',
  documents: './src/graphQL/**/*.ts',
  generates: {
    './src/graphQL/auto-generated.ts': {
      plugins: ['typescript', 'typescript-operations', 'typed-document-node'],
      config: {
        nonOptionalTypename: true,
      },
      // Add header comment to warn developers not to modify this file
      prepend: [
        '/* eslint-disable */',
        '/**',
        ' * ⚠️ 警告：このファイルは自動生成されています ⚠️',
        ' * ',
        ' * このファイルを直接編集しないでください。',
        ' * 変更は次回のコード生成時に上書きされます。',
        ' * ',
        ' * 変更が必要な場合は：',
        ' * 1. backend/graph/schema/*.graphqls を修正',
        ' *    または front/src/graphQL/ のサブディレクトリ内の .ts ファイルを修正',
        ' *    (Auth/, User/, Liquor/ など。このファイル自体は除く)',
        ' * 2. npm run codegen を実行して再生成',
        ' * ',
        ' * WARNING: This file is AUTO-GENERATED',
        ' * DO NOT EDIT this file directly.',
        ' * Changes will be overwritten on the next code generation.',
        ' */',
      ],
    },
  },
};
export default config;
